DP265 - fix invited admin users can't sign in
maplight/Digital-Petitions pull request #119
Opened 2022-09-19 22:47 UTC by lunox94

**Problem:**
Invited admin users can't sign in.

**Description:**
The invited users need to change the password the first time they sign in otherwise Cognito will not let the user sign in.

**Solution:**
Check if the sign in method returns a NEW_PASSWORD_REQUIRED challenge, if true then change the sign in UI for a new one that allows the user to enter a new password. Behind the scenes, when the user enters the new password a new method of Cognito is called using the previous sign in attempt result and this time will sign in the user in the app. Some extra job was done to redirect the user to the home page after the password was changed.

**Further work:**
In order to change the password some data is needed like the user's Given Name or Family Name. Right now this is hardcoded to a placeholder which makes the UI to show dummy data. The proposed approach to solve this is to include more form fields in the change password form.

2022-09-19 23:01 UTC, drmollineda requested changes

2022-09-19 23:01 UTC, drmollineda commented on src/app/auth/sign-in/sign-in.component.ts
> +    this.loading$ = merge(
There's probably no need to do so as I guess those statuses are mutually exclusive, but a more robust approach would be to do
```typescript
this.loading$ = combineLatest([this._signInLogic.loading$, this._completeNewPasswordLogic.loading$]).pipe(
    map(([loadSignIn, loadChangePassword]) => loadSignIn || loadChangePassword),
    startWith(false),
    shareReplay(1)
);
```

2022-09-20 01:20 UTC, lunox94 commented on src/app/auth/sign-in/sign-in.component.ts
> +    this.loading$ = merge(
I think in that case the startWith(false) needs to be on each loading$ observable, right?

2022-09-20 01:49 UTC, drmollineda approved these changes

2022-09-20 01:49 UTC, merged